// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Test

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Home
void ui_Home_screen_init(void);
lv_obj_t *ui_Home;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Image1;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label1;
void ui_event_Button3( lv_event_t * e);
lv_obj_t *ui_Button3;
lv_obj_t *ui_Label2;
void ui_event_Button4( lv_event_t * e);
lv_obj_t *ui_Button4;
void ui_event_Button5( lv_event_t * e);
lv_obj_t *ui_Button5;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Label4;
void ui_event_Button6( lv_event_t * e);
lv_obj_t *ui_Button6;
lv_obj_t *ui_Label5;
void ui_event_Button7( lv_event_t * e);
lv_obj_t *ui_Button7;
lv_obj_t *ui_Label6;
void ui_event_Button8( lv_event_t * e);
lv_obj_t *ui_Button8;
lv_obj_t *ui_Label7;
void ui_event_Button9( lv_event_t * e);
lv_obj_t *ui_Button9;
lv_obj_t *ui_Label8;
void ui_event_Button10( lv_event_t * e);
lv_obj_t *ui_Button10;
lv_obj_t *ui_Label9;
void ui_event_Button12( lv_event_t * e);
lv_obj_t *ui_Button12;
lv_obj_t *ui_Label11;


// SCREEN: ui_Sleep
void ui_Sleep_screen_init(void);
lv_obj_t *ui_Sleep;
void ui_event_Button11( lv_event_t * e);
lv_obj_t *ui_Button11;
lv_obj_t *ui_Label10;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btn_siri_test( e );
}
}
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btn_F11_test( e );
}
}
void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btn_sleep_test( e );
}
}
void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btn_14inch_test( e );
}
}
void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btn_dell_test( e );
}
}
void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btn_zoom_test( e );
}
}
void ui_event_Button7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btn_full_test( e );
}
}
void ui_event_Button8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btn_desktop_left( e );
}
}
void ui_event_Button9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btn_desktop_right( e );
}
}
void ui_event_Button10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btn_reboot_device( e );
}
}
void ui_event_Button12( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btn_sleepScreen_test( e );
}
}
void ui_event_Button11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      btn_wakeUp( e );
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 200, &ui_Home_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Home_screen_init();
ui_Sleep_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Home);
}
