// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Test

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void btn_siri_test(lv_event_t * e);
void btn_F11_test(lv_event_t * e);
void btn_sleep_test(lv_event_t * e);
void btn_14inch_test(lv_event_t * e);
void btn_dell_test(lv_event_t * e);
void btn_zoom_test(lv_event_t * e);
void btn_full_test(lv_event_t * e);
void btn_desktop_left(lv_event_t * e);
void btn_desktop_right(lv_event_t * e);
void btn_reboot_device(lv_event_t * e);
void btn_sleepScreen_test(lv_event_t * e);
void btn_wakeUp(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
