// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Test

#include "../ui.h"

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Home, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_btn_create(ui_Home);
lv_obj_set_width( ui_Button1, 64);
lv_obj_set_height( ui_Button1, 64);
lv_obj_set_x( ui_Button1, -183 );
lv_obj_set_y( ui_Button1, 82 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Button1);
lv_img_set_src(ui_Image1, &ui_img_siri_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 48
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button2 = lv_btn_create(ui_Home);
lv_obj_set_width( ui_Button2, 64);
lv_obj_set_height( ui_Button2, 64);
lv_obj_set_x( ui_Button2, 196 );
lv_obj_set_y( ui_Button2, 82 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"  Show\nDesktop");

ui_Button3 = lv_btn_create(ui_Home);
lv_obj_set_width( ui_Button3, 64);
lv_obj_set_height( ui_Button3, 32);
lv_obj_set_x( ui_Button3, -20 );
lv_obj_set_y( ui_Button3, -118 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Sleep");

ui_Button4 = lv_btn_create(ui_Home);
lv_obj_set_width( ui_Button4, 64);
lv_obj_set_height( ui_Button4, 64);
lv_obj_set_x( ui_Button4, -20 );
lv_obj_set_y( ui_Button4, -58 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button5 = lv_btn_create(ui_Home);
lv_obj_set_width( ui_Button5, 64);
lv_obj_set_height( ui_Button5, 64);
lv_obj_set_x( ui_Button5, -101 );
lv_obj_set_y( ui_Button5, -57 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Home);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -21 );
lv_obj_set_y( ui_Label3, -60 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"14");

ui_Label4 = lv_label_create(ui_Home);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -99 );
lv_obj_set_y( ui_Label4, -61 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Dell");

ui_Button6 = lv_btn_create(ui_Home);
lv_obj_set_width( ui_Button6, 64);
lv_obj_set_height( ui_Button6, 64);
lv_obj_set_x( ui_Button6, 62 );
lv_obj_set_y( ui_Button6, -58 );
lv_obj_set_align( ui_Button6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_Home);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 60 );
lv_obj_set_y( ui_Label5, -59 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Zoom");

ui_Button7 = lv_btn_create(ui_Home);
lv_obj_set_width( ui_Button7, 64);
lv_obj_set_height( ui_Button7, 64);
lv_obj_set_x( ui_Button7, 145 );
lv_obj_set_y( ui_Button7, -57 );
lv_obj_set_align( ui_Button7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_Home);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 145 );
lv_obj_set_y( ui_Label6, -59 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Full");

ui_Button8 = lv_btn_create(ui_Home);
lv_obj_set_width( ui_Button8, 64);
lv_obj_set_height( ui_Button8, 64);
lv_obj_set_x( ui_Button8, -23 );
lv_obj_set_y( ui_Button8, 82 );
lv_obj_set_align( ui_Button8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_Button8);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"< Desk");

ui_Button9 = lv_btn_create(ui_Home);
lv_obj_set_width( ui_Button9, 64);
lv_obj_set_height( ui_Button9, 64);
lv_obj_set_x( ui_Button9, 61 );
lv_obj_set_y( ui_Button9, 82 );
lv_obj_set_align( ui_Button9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label8 = lv_label_create(ui_Button9);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Desk>");

ui_Button10 = lv_btn_create(ui_Home);
lv_obj_set_width( ui_Button10, 64);
lv_obj_set_height( ui_Button10, 32);
lv_obj_set_x( ui_Button10, 64 );
lv_obj_set_y( ui_Button10, -118 );
lv_obj_set_align( ui_Button10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_Button10);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Reboot");

ui_Button12 = lv_btn_create(ui_Home);
lv_obj_set_width( ui_Button12, 64);
lv_obj_set_height( ui_Button12, 32);
lv_obj_set_x( ui_Button12, -101 );
lv_obj_set_y( ui_Button12, -118 );
lv_obj_set_align( ui_Button12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label11 = lv_label_create(ui_Button12);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Screen");

lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);

}
